Task/grow 310 agency plan selector
bufferapp/app-shell pull request #138
Opened 2021-12-13 01:37 UTC by daisymarie128

### Purpose
This PR aims to add the new Agency plan to the Plan Selector Modal.

Jira ticket: https://buffer.atlassian.net/browse/GROW-310

### Changes
This PR introduces changes to the logic and view of the Plan Selector.
- The Free Plan card has been removed and appears as a small footer section. Which required removing some logic from plan filtering. This  section only shows if:
   - The user is not on a Free Plan and has the ability to downgrade to Free
   - Will not show for Free users
- Agency Plan card has been added to the modal
- New hook `useDefaultSelectedPlan` created to simplify logic removing Free plan conditions
- Minor refactoring to styling for the PlanSelector modal

**User already on the Essentials Plan w/ monthly selected:**
<img width="1536" alt="Screen Shot 2021-12-13 at 11 57 34 am" src="https://user-images.githubusercontent.com/7763710/145739255-d8baf060-92f5-4bcc-9421-f67f78351720.png">

**User already on the Essentials Plan w/ yearly selected:**
<img width="1554" alt="Screen Shot 2021-12-13 at 12 09 18 pm" src="https://user-images.githubusercontent.com/7763710/145739278-0254a773-98fd-4e5e-a7ac-3cecfe9202b3.png">

**User already on the Free Plan w/ monthly selected:**
<img width="1526" alt="Screen Shot 2021-12-13 at 12 36 31 pm" src="https://user-images.githubusercontent.com/7763710/145739421-5b1a300e-052e-49fe-b5c1-add115e387ce.png">

**User already on the Free Plan w/ yearly selected:**
<img width="1537" alt="Screen Shot 2021-12-13 at 12 36 39 pm" src="https://user-images.githubusercontent.com/7763710/145739439-77018a49-e1dd-4600-837c-870fa72f0c14.png">

2021-12-14 17:03 UTC, dinostheo approved these changes
This looks great to me @daisymarie128 
I skimmed through the CSS part as I don't have enough knowledge to judge it 😅 
I do have some remarks regarding the Free plan. I'm wondering if this is the way we go design wise that we should stop sending the Free plan option from the server side, instead of trying to filter it. 
This doesn't block this PR at the moment, but if we remove the Free option from the server side then we should clean up the code that filters it out as well.

2022-01-05 18:59 UTC, hamstu requested changes
This looks great Daisy, I love how things are broken down and well tested. The only thing I noticed, as you'll see in my comments is a lot of your hooks can actually just be regular functions. The only reason to create a custom hook would be to encapsulate logic of another hook (often one of the 'base' hooks that React ships with.) Let me know if that makes sense!

2022-01-05 18:59 UTC, hamstu commented on packages/app-shell/src/components/Modal/modals/PlanSelector/hooks/useFeatureFlip.js
> +};
This is a great extraction of logic! My only comment is that naming it like a hook (`use***`) isn't necessary since it doesn't use any hooks itself (useState, useRef, etc.) so this could just be named and used as a plain function.

2022-01-05 18:59 UTC, hamstu commented on packages/app-shell/src/components/Modal/modals/PlanSelector/hooks/useFilteredListOfPlans.js
> +const useFilteredListOfPlans = (planOptions, planToExclude) => {
Same as prev. – this can be a plain function :)

2022-01-05 18:59 UTC, hamstu commented on packages/app-shell/src/components/Modal/modals/PlanSelector/hooks/useFilteredListOfPlans.test.jsx
> +    const { result } = renderHook(() =>
This test will be easier since you won't have to render a hook, but just test the function.

2022-01-05 18:59 UTC, hamstu commented on packages/app-shell/src/components/Modal/modals/PlanSelector/hooks/useDefaultSelectedPlan.js
> +const useDefaultSelectedPlan = (planOptions, user) => {
Coming back to this after looking at the two methods it calls, and I don't see any base hooks in use. Can be a plain function instead.

2022-01-06 17:47 UTC, hamstu approved these changes
✅   Awesome stuff Daisy!

2022-01-06 19:16 UTC, merged