WIP - Standalone channel quantity modal
bufferapp/app-shell pull request #190
Opened 2022-03-08 18:10 UTC by gisete

2022-03-10 14:18 UTC, merged

2022-03-10 14:38 UTC, dinostheo requested changes
This already looks great @gisete. It's great that you have merged since it's behind the feature flip. 
I have posted some questions and some remarks, with the latter needing some changes.

2022-03-10 14:38 UTC, dinostheo commented on packages/app-shell/src/components/Modal/modals/QuantityUpdate/components/CardBody.jsx
> +            openModal(MODALS.paymentMethod, data);
I notice that we are opening the payment method modal. Is there a flow that we will be asking the credit card details of a customer from the Quantity modal? I believe that we should already have this information, since the customer needs to be on a paying plan to work with this modal.

2022-03-10 14:38 UTC, dinostheo commented on packages/app-shell/src/components/Modal/modals/QuantityUpdate/index.jsx
> +            const planOptions =
We shouldn't need to dig the current plan from the `changePlanOptions`. I believe we should have all the information you need under that [subscription.plan and the plan.prices](https://github.com/bufferapp/core-authentication-service/blob/main/core-api/src/graphql/schema.graphql#L390-L427). 
If something is missing we should better add it to this structure instead of using the plan options.

2022-03-10 14:38 UTC, dinostheo commented on packages/app-shell/src/components/Modal/modals/QuantityUpdate/components/CardBody.jsx
> +                    New monthly cost: <strong>${newPrice}</strong>
It feels a bit that the 2 texts here might be conflicting `New monthly cost` and below `This will be billed every {planCycle} until canceled`, with `planCycle` to be either month or year. 
I'm might be understanding wrong though 😅

2022-03-10 14:52 UTC, cheahenry commented on packages/app-shell/src/components/Modal/modals/QuantityUpdate/components/CardBody.jsx
> +                    New monthly cost: <strong>${newPrice}</strong>
yeah I think we can just keep `New cost` and keep the planCycle in the text below like we do in the plan selector

2022-03-10 15:08 UTC, cheahenry commented on packages/app-shell/src/components/Modal/modals/QuantityUpdate/components/CardBody.jsx
> +    decreaseCounter,
You can probably also use `channelCountMessageStatus` for message status
https://github.com/bufferapp/app-shell/blob/2fc33dcfd7abcac04d4b05ead254aa2e088e993e/packages/app-shell/src/components/Modal/modals/PlanSelector/hooks/useChannelsCounter.js#L88

2022-03-10 16:12 UTC, dinostheo commented on packages/app-shell/src/components/Modal/modals/QuantityUpdate/components/CardBody.jsx
> +              openModal(MODALS.planSelector, data);
Thanks @gisete. 
Now I can picture what is happening here. I believe it is from the following design 
<img width="416" alt="Screen Shot 2022-03-10 at 17 08 41" src="https://user-images.githubusercontent.com/1632257/157705173-4e8cf0e8-f380-4a74-b556-80d88beba766.png">

and it feels that the intention is indeed, on `Change Plan` CTA to open the Plan Selector and change plan. In that case, your implementation is correct. 
Regarding if this is a good UX flow, I cannot really tell 😅 . I believe you were spot on implementing this design though 😄

2022-03-10 18:29 UTC, gisete commented
> 

Good tip @dinostheo. I haven't been intentional with squashing my commits before merging but I like when repos have that by default because it doesn't let me forget 🙂  I'll look into how I can turn it on for this repo.

2022-03-10 18:39 UTC, gisete commented on packages/app-shell/src/components/Modal/modals/QuantityUpdate/components/CardBody.jsx
> +              openModal(MODALS.planSelector, data);
@dinostheo I apologize, I thought you were talking about the action to the "Confirm & Pay" button, ignore my comment. Indeed this is meant to open the Plan Selector according to the design and I think it makes sense here. This copy and action is similar to the CTA that was added to the Channels page.

2022-03-10 19:11 UTC, gisete commented on packages/app-shell/src/components/Modal/modals/QuantityUpdate/components/CardBody.jsx
> +            openModal(MODALS.paymentMethod, data);
@dinostheo I created a sub-task in Jira for us to update the action here. I don't know yet how to go make a payment go through. Do you have an example in the code where that's being done?

2022-03-10 19:31 UTC, dinostheo commented on packages/app-shell/src/components/Modal/modals/QuantityUpdate/components/CardBody.jsx
> +            openModal(MODALS.paymentMethod, data);
@gisete In the following, we call the success modal https://github.com/bufferapp/app-shell/blob/main/packages/app-shell/src/components/Modal/modals/PlanSelector/index.jsx#L42
However, we need to do that after we have made a request to the server-side to persist the quantity change. We have a mutation for it on the API, [billingUpdateSubscriptionQuantity](https://github.com/bufferapp/core-authentication-service/blob/main/core-api/src/graphql/schema.graphql#L813-L817). We will need to create a mutation on the client-side to call this one and handle the success response by opening the success modal (or the error). 

[Here's how we make the API call](https://github.com/bufferapp/app-shell/blob/278ac9a29312883de572f79014d42742b0a2a83b/packages/app-shell/src/components/Modal/modals/PlanSelector/components/PlanSelectorContainer.jsx#L111-L122) in the case of the Plan Selector (it's a different mutation here)
and here's [how we handle the response](https://github.com/bufferapp/app-shell/blob/278ac9a29312883de572f79014d42742b0a2a83b/packages/app-shell/src/components/Modal/modals/PlanSelector/components/PlanSelectorContainer.jsx#L213-L224)

All these might be very new due to GraphQL, so happy to pair on it, on Monday or any other day next week 😃

2022-03-14 19:11 UTC, gisete commented on packages/app-shell/src/components/Modal/modals/QuantityUpdate/index.jsx
> +            const planOptions =
@dinostheo I created a PR to address this https://github.com/bufferapp/app-shell/pull/201