Add Confirmation Screen
bufferapp/app-shell pull request #20
Opened 2021-03-10 20:21 UTC by gmzjuliana

2021-03-12 13:04 UTC, gmzjuliana commented on packages/app-shell/src/Confirmation/index.jsx
> +              startedTrial={startedTrial} //data.isTrial
hey @federicoweber i used mocks in here to be able to test it but on Monday we can make the changes in the paymentMethod/startTrialModal to hook it up so we pass the selectedPlan and 2 bools for onlyUpdatedCardDetails and startedTrial

2021-03-15 22:11 UTC, federicoweber requested changes
This is looking great @gmzjuliana, I left a few small comments, but the only blocker is with the test data we are passing to the confirmation modal :).

Feel free to ship this once that it's ok.

Thanks!

2021-03-15 22:11 UTC, federicoweber commented on packages/app-shell/src/Confirmation/hooks/useCopy.js
> +  if (onlyUpdatedCardDetails) {
Do you think we can remove the `onlyUpdatedCardDetails` check and just set it as the default option, in case there is no plan and `startedTrial` is false?

2021-03-15 22:11 UTC, federicoweber commented on packages/app-shell/src/Confirmation/hooks/useCopy.js
> +const useCopy = ({ planName, startedTrial, onlyUpdatedCardDetails }) => {
this feels more like a `getCopy` function then an hook to me, as we are not using any react specific logic in here (states, ref, …) 😉

2021-03-15 22:11 UTC, federicoweber commented on packages/app-shell/src/Confirmation/index.jsx
> +              startedTrial={startedTrial} //data.isTrial
I see you updated the callbacks but you are still using the test values in here 😉.

2021-03-16 20:34 UTC, merged