add trial banner to app shell
bufferapp/app-shell pull request #37
Opened 2021-03-30 23:25 UTC by gmzjuliana

2021-03-30 23:38 UTC, gmzjuliana commented on packages/app-shell/src/index.jsx
> +              text={trialBannerString}
@federicoweber I would've liked to rather send a customHtml but I think since it's react, it's not HTML and I can't off the top of my head remember what we have to do to make it react.. something with renderDOM 🤔  in any case, I can look at it tomorrow if you can't remember either but I wanted to note it!

2021-03-31 14:23 UTC, gmzjuliana commented on packages/app-shell/src/index.jsx
> +              text={trialBannerString}
hey @federicoweber I was able to look at this today and what I was looking for was `ReactDOM.renderToString()` https://reactjs.org/docs/react-dom-server.html however, the click handler doesn't fire if I use that 🤔 maybe something we could look at together

2021-03-31 15:49 UTC, federicoweber commented on packages/app-shell/src/index.jsx
> +              text={trialBannerString}
Hey @gmzjuliana, yeah that makes sense because, you will be outputting pure HTML, so react won't be working at that stage.

But what is the reason you want to pass down HTML instead of a Component?

2021-03-31 17:38 UTC, gmzjuliana commented on packages/app-shell/src/index.jsx
> +              text={trialBannerString}
hey @federicoweber, jejeje I'd expect the click handler to still fire though, clicks are still html 🤔 I tried juuust html and the click handler for a <button onclick="function"> doesn't work either 🤔 I'd love to understand why, even if we don't end up using it

The reason I want to pass HTML is so that the plan name and remaining time can be in bold. Can you think of another way to do that without customHTML? Perhaps the screen shot in the description is misleading, this is what it currently looks like: 
![image](https://user-images.githubusercontent.com/54291087/113186944-e0e8eb80-921d-11eb-8d53-eac70b91ced0.png)

2021-04-05 15:11 UTC, merged

2021-04-05 15:12 UTC, federicoweber requested changes
Hey @gmzjuliana this is looking great, but let's make sure we are limiting this to OB users before merging it in.