test staging env
bufferapp/app-shell pull request #69
Opened 2021-06-04 00:45 UTC by federicoweber

2021-06-10 12:29 UTC, kiriappeee commented
heyya @federicoweber . I think you are on the right track here for getting this deployed. I think what you want to try first though is to build the image locally and see if it runs. When I tried to do that, I got an error where it said that the modules could not be imported. The error I get is:


```
Starting the development server...

Failed to compile.

./src/App.js
Module not found: Can't resolve '@bufferapp/app-shell' in '/app/packages/app/src'
Compiling...
Failed to compile.

./src/App.js
Module not found: Can't resolve '@bufferapp/app-shell' in '/app/packages/app/src'
```

I ran the following: 

```
docker build -t appshell:test .
docker run --rm appshell:test
```

to test. Once we have this step sorted, we can move forward with more config very quickly 😃 .

2021-06-10 23:57 UTC, federicoweber commented
Thanks for looking into this @kiriappeee, with the last changes we are now building and serving the production version of the apps.
And I can see the container it's running properly, but this branch is not triggering the deployment anymore 😕

2021-06-10 23:59 UTC, federicoweber commented on package.json
> +    "serve:ssl": "serve -l 3000 --ssl-cert ../reverseproxy/certs/local.buffer.com.crt --ssl-key ../reverseproxy/certs/local.buffer.com.key ./packages/app/build",
@kiriappeee at the moment I'm using the `serve` script to run the app but we will need to use `serve:ssl` to access serve the secure page and access the APIs Gateway.
In the script I'm using the local certificates, but not sure how to change it to run in the staging container 🙂 .

2021-06-16 13:32 UTC, kiriappeee commented on helm/testenv.yaml
> +    memory: 32Mi
```suggestion
```

2021-06-16 13:34 UTC, kiriappeee commented on helm/testenv.yaml
> +    memory: 32Mi
Sorry I didn't add more description here. Wasn't sure I'd be able to commit the suggestion if I did. I ran into a problem when I deployed it today in the evening. The pod crashed instantly and did not start up. I checked and it said OOM killed. My guess is that the resources aren't enough since it's just 32 Mi that's been added as a limit. So I've removed the limits to test that assumption for now.

2021-06-16 13:35 UTC, kiriappeee commented
Heyya @federicoweber . I've begun testing this. Just to clarify on how we can deploy this until we've added this to the pipeline:

`@bufferbot servicedeploy task/staging to app-shell` will deploy the service.

2021-06-16 13:39 UTC, kiriappeee requested changes

2021-06-16 13:39 UTC, kiriappeee commented on Dockerfile
> +CMD yarn build && yarn serve
@federicoweber  I think this should just be `yarn serve`? We shouldn't be running `yarn build` as a startup command. The assets should be built already at this point I believe.

2021-06-16 13:43 UTC, kiriappeee commented on Dockerfile
> +CMD yarn build && yarn serve
The error I'm seeing in the container now is:

```
yarn run v1.22.5
$ npm-run-all --parallel build:app build:app-shell
Killed
```

This makes sense since the build is probably taking a lot of memory. IF this is a must, then we'd need to bump the resource request numbers to ensure that the container is started with more resources allocated to it by default.

In any case, I think starting a container with just 16 Mi might be causing trouble if the pod is placed into a machine without more resources to expand. For context, [publish starts with 80 Mi for memory and 150m for CPU](https://github.com/bufferapp/buffer-publish/blob/main/helm/buffer-publish.yaml#L22-L24)

2021-06-16 13:44 UTC, kiriappeee commented on Dockerfile
> +CMD yarn build && yarn serve
```suggestion
RUN yarn add -W serve && yarn build
CMD yarn serve
```

2021-06-16 13:47 UTC, kiriappeee commented on package.json
> +    "serve:ssl": "serve -l 3000 --ssl-cert ../reverseproxy/certs/local.buffer.com.crt --ssl-key ../reverseproxy/certs/local.buffer.com.key ./packages/app/build",
@federicoweber I think we can tackle this as soon as we get this up and running for the first time. My hunch is that this might not be an issue. Our apps run behind HTTPS proxies by default. But if the app needs to have an SSL certificate of its own embedded and it needs to run as an HTTPS app (i.e., not an HTTP app sitting behind an HTTPS proxy), then we'll need to do some additional work here which we can figure out soon.

2021-06-16 17:04 UTC, federicoweber commented on package.json
> +    "serve:ssl": "serve -l 3000 --ssl-cert ../reverseproxy/certs/local.buffer.com.crt --ssl-key ../reverseproxy/certs/local.buffer.com.key ./packages/app/build",
ah good one, I think the proxy will be enough. Will change the config so it's not forcing certificates on staging

2021-06-16 17:08 UTC, federicoweber commented on Dockerfile
> +CMD yarn build && yarn serve
Ah that makes sense. What do you think could be a good setting? 32 Mi? I think we won't need much CPU once it's built.

2021-06-17 19:17 UTC, federicoweber commented
This is looking great @kiriappeee 
![image](https://user-images.githubusercontent.com/992920/122459538-e4ab2500-cf65-11eb-9bb6-52164067e2db.png)

Thanks for the help 🌮 🙌 .

Going to merge this is. Do you think we can enable automatic deployment for PRs?

2021-06-17 20:43 UTC, merged