Add GraphQL business logic to handle OB Migration
bufferapp/app-shell pull request #78
Opened 2021-07-09 01:50 UTC by federicoweber

2021-07-09 01:51 UTC, federicoweber commented on packages/app-shell/src/common/graphql/billing.js
> +    $billingMigrateToOneBufferOrganizationId: String!
hey @dinostheo and @esclapes I see this hasn't been exposed to the APIs Gateway yet. Is there any blocker?

2021-07-09 01:56 UTC, federicoweber commented on packages/app-shell/src/common/graphql/billing.js
> +      }
This is a bit redundant, but it's used to properly override the data from the account query, we should be able to clean this up once we return an `ID` for the `billing` object.

2021-07-09 20:38 UTC, dinostheo commented on packages/app-shell/src/common/graphql/billing.js
> +      }
@federicoweber `Billing` does have an `id`. It is the `organizationID`, but it should work well for the cache. 

Related to schema IDs:
As part of the working groups I started research on this subject as well and I have documented the finding so far in [this paper](https://paper.dropbox.com/doc/RFC-Apollo-client-InMemoryCache-and-Object-ids--BOPpXfO~Xh7En9bRBfeJ2cU9Ag-bN3qCCI3Q1lFErDcWdB9O)

2021-07-09 20:39 UTC, dinostheo commented on packages/app-shell/src/common/graphql/billing.js
> +    $billingMigrateToOneBufferOrganizationId: String!
@federicoweber you are right. That's my fault. 
I forgot to change the API gateway when I merged the migration PR. I will do it on Monday morning.

2021-07-12 08:00 UTC, esclapes approved these changes
This looks good to me @federicoweber :taco: :+1: 

It's great to see an example of typed errors, I pinged Maya and Joe below to discuss the pattern because that's part of the backend wg current agenda, but that should not block this PR :rocket:

2021-07-12 13:39 UTC, esclapes requested changes
Hey @federicoweber I was chatting with Phil about this and we thought it may be a good idea to make two changes before merge. That way we can use this repo to explore/promote new best practices :

* let's use a Fragment to avoid the repetition on the queried fields
* let's figure out a way to use the underlying `__typename` instead of accessing a property like `userFriendlyMessage` to check if it's an error.

Thanks! :raised_hands:

2021-07-12 16:01 UTC, federicoweber commented on packages/app-shell/src/common/graphql/billing.js
> +    $billingMigrateToOneBufferOrganizationId: String!
thanks @dinostheo

2021-07-12 16:05 UTC, federicoweber commented on packages/app-shell/src/common/graphql/billing.js
> +      }
Good one @esclapes, you are spot on, that's why I mentioned we should use IDs instead. With IDs, we shouldn't request a refetch either, as Apollo Client we be handling this for us.

@dinostheo that's great news, will change this to use the ID then. Thanks!

2021-07-12 16:07 UTC, federicoweber commented on packages/app-shell/src/common/hooks/useMigrateToOB.js
> +  }, [data, mutationError]);
Hey @esclapes, I get your point, but I actually prefer to use the field in here instead of the type, as what we really care for is to show the `userFriendlyMessage` if that's available, so this feels a bit more explicit. As for the `mutationError` that could happen for any reason, including lost connection, so we will always need to check for that as well.

2021-07-13 07:22 UTC, esclapes commented on packages/app-shell/src/common/graphql/billing.js
> +          id
Hey @federicoweber, I am not sure I understand this change.

When the mutation executes, most `billing` details will change. If we only receive back the `id`, how are the new value going to be updated in the cache?

My hunch is that by only requesting the `id` the billing fields for the organization will be out of date. I may be missing something, but if we create [BillingFields fragment](https://www.apollographql.com/docs/react/data/fragments/) we could define the list of fields the AppShell cares about and use the fragment in all 3 places:
* `currentOrganization.billing`
* `organizations.billing`
* `billingMigrateToOneBuffer`

If the fragment includes the `id`, I would expect the cache invalidation to work fine without need to re-fetch. I may be missing something about how caching works, though, so.

2021-07-13 07:24 UTC, esclapes commented on packages/app-shell/src/common/hooks/useMigrateToOB.js
> +  }, [data, mutationError]);
> I get your point, but I actually prefer to use the field in here instead of the type, as what we really care for is to show the userFriendlyMessage if that's available

Sound good to me, @federicoweber :+1:  This won't be hard to iterate on as we introduce new types of errors. cc @philippemiguet

2021-07-13 15:33 UTC, federicoweber commented on packages/app-shell/src/common/graphql/billing.js
> +          id
You are right @esclapes I was under the impression that getting back the ID would have been enough to trigger a cache invalidation, but it won't work by itself unless the rest of the fields are present.
I like your approach, we could also solve this by triggering a re-fetch,

```
const [migrateToOB, { data, error: mutationError }] = useMutation(
  MIGRATE_TO_OB,
  {
    refetchQueries: [{ query: QUERY_ACCOUNT }],
  }
);

```
but the Fragment is more elegant and save us a request.

2021-07-14 12:58 UTC, esclapes approved these changes
LGTM @federicoweber! Nice example of Fragments that we have now :heart_eyes:

2021-07-14 18:49 UTC, merged

2021-07-15 10:15 UTC, philippemiguet commented
Great use of Fragment there! 🙌