Grow 195 ux navbar
bufferapp/app-shell pull request #93
Opened 2021-08-16 06:11 UTC by daisymarie128

Link to ticket: https://buffer.atlassian.net/browse/GROW-195

This PR updates the styling of the app navbar. You can find the design specs in the ticket linked.

### 🤹‍♂️Main things happening in the PR:
- New **_"Apps"_** dropdown menu added.
- Tweaks to hover states and style changes
- New 1200px breakpoint was added to reduce some padding in navbar.
- Moved out dropdown constants to a utils file to try and move some code out from the `.../components/NavBar/index` file. I chose to move this out to make it easier to find information in this file 

### ❓ Outstanding question I have to check in with design about:
- Apps & Help dropdown don't match the Figma file but I used the `@bufferapp/ui/DropdownMenu` to handle styling. I'm just unsure if this was the correct approach or I should build a new custom dropdown? ❓
**Current styling:**
<img width="490" alt="Screen Shot 2021-08-16 at 3 54 48 pm" src="https://user-images.githubusercontent.com/7763710/129518669-e954efdd-89a9-432a-bcef-621d34af0bc6.png">

**What Figma shows:**
<img width="194" alt="Screen Shot 2021-08-16 at 4 10 13 pm" src="https://user-images.githubusercontent.com/7763710/129518746-6f7e5e72-bb34-4558-a6b2-0b73df3dca9b.png">

### Screenshots:
<img width="1307" alt="Screen Shot 2021-08-16 at 3 52 16 pm" src="https://user-images.githubusercontent.com/7763710/129518481-2923a6e0-7fa0-44e4-b196-5124cc7abf6a.png">

Hover state:
<img width="1305" alt="Screen Shot 2021-08-16 at 3 52 25 pm" src="https://user-images.githubusercontent.com/7763710/129518510-04bddda9-e0fb-4c36-9683-5482fd478399.png">

Active state: 
<img width="1307" alt="Screen Shot 2021-08-16 at 3 53 59 pm" src="https://user-images.githubusercontent.com/7763710/129518548-3b1ff85d-6a0c-4e6c-8ace-359f938c4d77.png">

Apps dropdown:
<img width="1306" alt="Screen Shot 2021-08-16 at 3 54 54 pm" src="https://user-images.githubusercontent.com/7763710/129518578-38d69928-1a6d-4c95-8e2a-db8027bd4a9c.png">

2021-08-16 06:17 UTC, daisymarie128 commented on packages/app-shell/src/components/NavBar/components/NavBarMenu/NavBarMenu.jsx
> +    isImpersonation: PropTypes.bool.isRequired,
📓Note: I added this here to fix an eslint error stating this was never defined. (Wasn't sure how to check if this property is always passed through in the data of `user`)

2021-08-16 06:20 UTC, daisymarie128 commented on packages/app-shell/src/components/NavBar/components/NavBarProducts/NavBarProducts.jsx
> +const lighterGreyHoverState = 'rgba(218, 221, 238, 0.25);';
📓 Note: This const has been declared in 3~ different spots. I wasn't sure if there was a better way to share this variable around or where to put it as most colors come from `@buffer/ui/style` 🤔 if you have any suggestions let me know 😄

2021-08-30 21:22 UTC, federicoweber requested changes
Hey @daisymarie128 thanks for working on this. 
I left a couple of small comments I would like to address before shipping this but overall it's looking solid 🌮.

2021-08-30 21:22 UTC, federicoweber commented on packages/app-shell/src/components/NavBar/components/NavBarMenu/NavBarMenu.jsx
> +    isImpersonation: PropTypes.bool.isRequired,
Good one 🤔, theoretically this property is always present but I'm not sure we want to make it as a requirement as the NavBar will be able to properly render even if it's missing.
I would suggest setting it as an optional parameter with the default set to `false`

2021-08-30 21:22 UTC, federicoweber commented on packages/app-shell/src/components/NavBar/components/NavBarMenu/style.js
> +const lighterGreyHoverState = 'rgba(218, 221, 238, 0.25);'
Hey @daisymarie128 I think for colors we want to use the ones defined in the [UI guidelines](https://www.notion.so/buffer/cab977d026c748009c4d9c70b08a21f5?v=6fa298b9773b40fb8636c38c055fa8a3&p=80f6c8b6ec6d45edab660b5c34fc9424) as much as possible. 
Any specific reason we are changing this one?

2021-08-30 21:22 UTC, federicoweber commented on packages/app-shell/src/components/NavBar/components/NavBarProducts/NavBarProducts.jsx
> +const lighterGreyHoverState = 'rgba(218, 221, 238, 0.25);';
Great intuition there. Feels like the colors exports in UI will be a better place for this.
But I will also double-check with the Desing team if we want to add an extra one 🙂.

2021-08-30 21:22 UTC, federicoweber commented on packages/app-shell/src/components/NavBar/index.jsx
> +} from './utils/dropdown-items';
Great call abstracting those 💯.

2021-08-31 00:50 UTC, daisymarie128 commented on packages/app-shell/src/components/NavBar/components/NavBarProducts/NavBarProducts.jsx
> +const lighterGreyHoverState = 'rgba(218, 221, 238, 0.25);';
@federicoweber I've removed these styles now and replaced with a gray from buffer/ui 😊

2021-08-31 22:39 UTC, federicoweber approved these changes
Looks great, thanks @daisymarie128 
![ship it](https://media.giphy.com/media/mi6DsSSNKDbUY/giphy-downsized-large.gif?cid=ecf05e47l42dsotylrwo1jtcxajy4ywv9haz8zfsjzpy9zya&rid=giphy-downsized-large.gif&ct=g)

2021-08-31 22:44 UTC, merged